custom:
  serverIP: 127.0.0.1
  submitInterval: 300000

spring:
  application:
    name: stock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${custom.serverIP}:3306/ldb?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  redis:
    host: ${custom.serverIP}
    port: 6379
    database: 1
  rabbitmq:
    addresses: ${custom.serverIP}
    port: 5672
    username: admin
    password: admin
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
  
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
    
server:
  port: 8012
  servlet:
    context-path: /stock
    session:
      timeout: 120

